// TinyGFXPanelSH1106_128x64
//
// The 1.3 inch module, sold as an "SSD1306" more often than not.
// 132 columns of memory behind 128 of glass, so the picture sits
// two columns in - which the driver derives, the glass being
// centred.
//
// Generated by tools/gen_panels.py - edit the catalogue there, not this file.
// If the picture is wrong, docs/PANEL_TUNING.ja.md says which line to change.
#pragma once
#ifdef TINYGFX_DRIVER_SH1106_INCLUDED
#error "TinyGFX: one SH1106 panel per sketch. Include this header rather than <TinyGFX/DriverSH1106.h>, and do not include a second panels/SH1106_*.h - the second would be silently ignored and its panel driven with the first one's values."
#endif
#include "../DriverSH1106.h"

class TinyGFXPanelSH1106_128x64 : public TinyGFXDriverSH1106 {
 public:
  static const int16_t kWidth = 128;
  static const int16_t kHeight = 64;
  /// Size the framebuffer with this, so it cannot be got wrong:
  ///   static uint8_t fb[TinyGFXPanelSH1106_128x64::kBufferBytes];
  static const uint16_t kBufferBytes = (uint16_t)(kWidth * kHeight / 8);

  /// `bufferPages` renders in a band of that many pages; 0 is the whole screen.
  TinyGFXPanelSH1106_128x64(TinyGFXBus& bus, uint8_t* buffer, int16_t bufferPages = 0)
      : TinyGFXDriverSH1106(bus, buffer, kWidth, kHeight, bufferPages) {}
};
