// TinyGFXPanelSSD1306_128x64_SeqCom
//
// A 128x64 whose COM lines are wired sequentially.
// Try this one when the 128x64 comes out as every other row.
//
// Generated by tools/gen_panels.py - edit the catalogue there, not this file.
// If the picture is wrong, docs/PANEL_TUNING.ja.md says which line to change.
#pragma once
#ifdef TINYGFX_DRIVER_SSD1306_INCLUDED
#error "TinyGFX: one SSD1306 panel per sketch. Include this header rather than <TinyGFX/DriverSSD1306.h>, and do not include a second panels/SSD1306_*.h - the second would be silently ignored and its panel driven with the first one's values."
#endif

// This glass wires its COM lines sequentially, not alternately.
#define TINYGFX_SSD1306_COM_PINS 0x02
#include "../DriverSSD1306.h"

class TinyGFXPanelSSD1306_128x64_SeqCom : public TinyGFXDriverSSD1306 {
 public:
  static const int16_t kWidth = 128;
  static const int16_t kHeight = 64;
  /// Size the framebuffer with this, so it cannot be got wrong:
  ///   static uint8_t fb[TinyGFXPanelSSD1306_128x64_SeqCom::kBufferBytes];
  static const uint16_t kBufferBytes = (uint16_t)(kWidth * kHeight / 8);

  /// `bufferPages` renders in a band of that many pages; 0 is the whole screen.
  TinyGFXPanelSSD1306_128x64_SeqCom(TinyGFXBus& bus, uint8_t* buffer, int16_t bufferPages = 0)
      : TinyGFXDriverSSD1306(bus, buffer, kWidth, kHeight, bufferPages) {}
};

// The name of the panel this sketch drives, so that it is written once:
//
//   TINYGFX_PANEL panel(bus);
//
// **Two panels and this disappears** - the second header to arrive removes it,
// because there is then no such thing as "the" panel. Name them explicitly.
#ifdef TINYGFX_PANEL_CLAIMED
#undef TINYGFX_PANEL
#else
#define TINYGFX_PANEL_CLAIMED 1
#define TINYGFX_PANEL TinyGFXPanelSSD1306_128x64_SeqCom
#endif
