// TinyGFXPanelSSD1306_48x64
//
// The 0.71 inch portrait module.
//
// Generated by tools/gen_panels.py - edit the catalogue there, not this file.
// If the picture is wrong, docs/PANEL_TUNING.ja.md says which line to change.
#pragma once
#ifdef TINYGFX_DRIVER_SSD1306_INCLUDED
#error "TinyGFX: one SSD1306 panel per sketch. Include this header rather than <TinyGFX/DriverSSD1306.h>, and do not include a second panels/SSD1306_*.h - the second would be silently ignored and its panel driven with the first one's values."
#endif
#include "../DriverSSD1306.h"

class TinyGFXPanelSSD1306_48x64 : public TinyGFXDriverSSD1306 {
 public:
  static const int16_t kWidth = 48;
  static const int16_t kHeight = 64;
  /// Size the framebuffer with this, so it cannot be got wrong:
  ///   static uint8_t fb[TinyGFXPanelSSD1306_48x64::kBufferBytes];
  static const uint16_t kBufferBytes = (uint16_t)(kWidth * kHeight / 8);

  /// `bufferPages` renders in a band of that many pages; 0 is the whole screen.
  TinyGFXPanelSSD1306_48x64(TinyGFXBus& bus, uint8_t* buffer, int16_t bufferPages = 0)
      : TinyGFXDriverSSD1306(bus, buffer, kWidth, kHeight, bufferPages) {}
};
