// TinyGFXPanelST7796_320x480
//
// The 3.5 inch breakout. Its memory is exactly the panel, so
// nothing is offset.
//
// Generated by tools/gen_panels.py - edit the catalogue there, not this file.
// If the picture is wrong, docs/PANEL_TUNING.ja.md says which line to change.
#pragma once
#ifdef TINYGFX_DRIVER_ST7796_INCLUDED
#error "TinyGFX: one ST7796 panel per sketch. Include this header rather than <TinyGFX/DriverST7796.h>, and do not include a second panels/ST7796_*.h - the second would be silently ignored and its panel driven with the first one's values."
#endif
#include "../DriverST7796.h"

class TinyGFXPanelST7796_320x480 : public TinyGFXDriverST7796 {
 public:
  static const int16_t kWidth = 320;
  static const int16_t kHeight = 480;

  explicit TinyGFXPanelST7796_320x480(TinyGFXBus& bus, int8_t rst = -1)
      : TinyGFXDriverST7796(bus, kWidth, kHeight, rst) {}
};

// The name of the panel this sketch drives, so that it is written once:
//
//   TINYGFX_PANEL panel(bus);
//
// **Two panels and this disappears** - the second header to arrive removes it,
// because there is then no such thing as "the" panel. Name them explicitly.
#ifdef TINYGFX_PANEL_CLAIMED
#undef TINYGFX_PANEL
#else
#define TINYGFX_PANEL_CLAIMED 1
#define TINYGFX_PANEL TinyGFXPanelST7796_320x480
#endif
