// TinyGFXPanelST7735_128x160
//
// The 1.8 inch module. Glass centred in the 132x162 memory.
//
// Generated by tools/gen_panels.py - edit the catalogue there, not this file.
// If the picture is wrong, docs/PANEL_TUNING.ja.md says which line to change.
#pragma once
#ifdef TINYGFX_DRIVER_ST7735_INCLUDED
#error "TinyGFX: one ST7735 panel per sketch. Include this header rather than <TinyGFX/DriverST7735.h>, and do not include a second panels/ST7735_*.h - the second would be silently ignored and its panel driven with the first one's values."
#endif
#include "../DriverST7735.h"

class TinyGFXPanelST7735_128x160 : public TinyGFXDriverST7735 {
 public:
  static const int16_t kWidth = 128;
  static const int16_t kHeight = 160;

  explicit TinyGFXPanelST7735_128x160(TinyGFXBus& bus, int8_t rst = -1)
      : TinyGFXDriverST7735(bus, kWidth, kHeight, rst) {
    setGramSize(132, 162);
    setOffset(2, 1);
  }
};
