// TinyGFXPanelST7789_240x320
//
// The full 2.0 inch panel, filling its memory exactly.
//
// Generated by tools/gen_panels.py - edit the catalogue there, not this file.
// If the picture is wrong, docs/PANEL_TUNING.ja.md says which line to change.
#pragma once
#ifdef TINYGFX_DRIVER_ST7789_INCLUDED
#error "TinyGFX: one ST7789 panel per sketch. Include this header rather than <TinyGFX/DriverST7789.h>, and do not include a second panels/ST7789_*.h - the second would be silently ignored and its panel driven with the first one's values."
#endif
#include "../DriverST7789.h"

class TinyGFXPanelST7789_240x320 : public TinyGFXDriverST7789 {
 public:
  static const int16_t kWidth = 240;
  static const int16_t kHeight = 320;

  explicit TinyGFXPanelST7789_240x320(TinyGFXBus& bus, int8_t rst = -1)
      : TinyGFXDriverST7789(bus, kWidth, kHeight, rst) {}
};
