// TinyGFXPanelST7789_240x280
//
// The 1.69 inch module. Full width, 40 rows short of the memory,
// and centred down it.
//
// Generated by tools/gen_panels.py - edit the catalogue there, not this file.
// If the picture is wrong, docs/PANEL_TUNING.ja.md says which line to change.
#pragma once
#ifdef TINYGFX_DRIVER_ST7789_INCLUDED
#error "TinyGFX: one ST7789 panel per sketch. Include this header rather than <TinyGFX/DriverST7789.h>, and do not include a second panels/ST7789_*.h - the second would be silently ignored and its panel driven with the first one's values."
#endif
#include "../DriverST7789.h"

class TinyGFXPanelST7789_240x280 : public TinyGFXDriverST7789 {
 public:
  static const int16_t kWidth = 240;
  static const int16_t kHeight = 280;

  explicit TinyGFXPanelST7789_240x280(TinyGFXBus& bus, int8_t rst = -1)
      : TinyGFXDriverST7789(bus, kWidth, kHeight, rst) {
    setGramSize(240, 320);
    setOffset(0, 20);
  }
};

// The name of the panel this sketch drives, so that it is written once:
//
//   TINYGFX_PANEL panel(bus);
//
// **Two panels and this disappears** - the second header to arrive removes it,
// because there is then no such thing as "the" panel. Name them explicitly.
#ifdef TINYGFX_PANEL_CLAIMED
#undef TINYGFX_PANEL
#else
#define TINYGFX_PANEL_CLAIMED 1
#define TINYGFX_PANEL TinyGFXPanelST7789_240x280
#endif
