// TinyGFXPanelST7735_128x128
//
// The 1.44 inch square module. **Not centred vertically** - it
// sits 3 rows down a 162-row memory, not 17.
//
// Generated by tools/gen_panels.py - edit the catalogue there, not this file.
// If the picture is wrong, docs/PANEL_TUNING.ja.md says which line to change.
#pragma once
#ifdef TINYGFX_DRIVER_ST7735_INCLUDED
#error "TinyGFX: one ST7735 panel per sketch. Include this header rather than <TinyGFX/DriverST7735.h>, and do not include a second panels/ST7735_*.h - the second would be silently ignored and its panel driven with the first one's values."
#endif
#include "../DriverST7735.h"

class TinyGFXPanelST7735_128x128 : public TinyGFXDriverST7735 {
 public:
  static const int16_t kWidth = 128;
  static const int16_t kHeight = 128;

  explicit TinyGFXPanelST7735_128x128(TinyGFXBus& bus, int8_t rst = -1)
      : TinyGFXDriverST7735(bus, kWidth, kHeight, rst) {
    setGramSize(132, 162);
    setOffset(2, 3);
  }
};

// The name of the panel this sketch drives, so that it is written once:
//
//   TINYGFX_PANEL panel(bus);
//
// **Two panels and this disappears** - the second header to arrive removes it,
// because there is then no such thing as "the" panel. Name them explicitly.
#ifdef TINYGFX_PANEL_CLAIMED
#undef TINYGFX_PANEL
#else
#define TINYGFX_PANEL_CLAIMED 1
#define TINYGFX_PANEL TinyGFXPanelST7735_128x128
#endif
