// TinyGFXPanelST7735_128x160_FlushRgb
//
// A 1.8 inch whose glass is flush with the memory **and wired RGB
// rather than BGR**. Try this when the 128x160 comes out shifted
// two pixels with red and blue swapped.
//
// Generated by tools/gen_panels.py - edit the catalogue there, not this file.
// If the picture is wrong, docs/PANEL_TUNING.ja.md says which line to change.
#pragma once
#ifdef TINYGFX_DRIVER_ST7735_INCLUDED
#error "TinyGFX: one ST7735 panel per sketch. Include this header rather than <TinyGFX/DriverST7735.h>, and do not include a second panels/ST7735_*.h - the second would be silently ignored and its panel driven with the first one's values."
#endif
#include "../DriverST7735.h"

class TinyGFXPanelST7735_128x160_FlushRgb : public TinyGFXDriverST7735 {
 public:
  static const int16_t kWidth = 128;
  static const int16_t kHeight = 160;

  explicit TinyGFXPanelST7735_128x160_FlushRgb(TinyGFXBus& bus, int8_t rst = -1)
      : TinyGFXDriverST7735(bus, kWidth, kHeight, rst) {
    setGramSize(132, 162);
    setRgbOrder(false);   // this glass is wired RGB
  }
};

// The name of the panel this sketch drives, so that it is written once:
//
//   TINYGFX_PANEL panel(bus);
//
// **Two panels and this disappears** - the second header to arrive removes it,
// because there is then no such thing as "the" panel. Name them explicitly.
#ifdef TINYGFX_PANEL_CLAIMED
#undef TINYGFX_PANEL
#else
#define TINYGFX_PANEL_CLAIMED 1
#define TINYGFX_PANEL TinyGFXPanelST7735_128x160_FlushRgb
#endif
