"""Builds the verification sketch from what the converter wrote.

Reads `images.h` - **one bundled header holding every image**, which is what
GfxImageToolJs emits for a project - and pairs each `TinyGFXImageRef` in it
with the picture of the same name in `expected/`.

The layout is the tool's own: sources in `images/`, the bundle beside it. **This
sketch is arranged the way a user's sketch is**, so the include under test is
the include they will write.

The generator exists so that **adding a case needs no code**: drop a `.png` in
`images/`, name it in `images/.imagesconfig`, run `regen.py`. It runs at pytest
collection time and writes `image_oracle.ino`.
"""

import re
from pathlib import Path

HERE = Path(__file__).parent
GENERATED = HERE / "images.h"
EXPECTED = HERE / "expected"

# `static const TinyGFXImageRef iconRef = {&icon, &tinygfxImageRlepal4Ops};`
REF = re.compile(
    r"static const TinyGFXImageRef\s+(\w+)Ref\s*=\s*"
    r"\{\s*&\w+\s*,\s*&tinygfxImage(\w+)Ops\s*\}")

HEAD = '''// **Does a generated image header draw exactly the converter's expected image?**
//
// The oracle specified by GfxImageToolJs spec 15.2. TinyGFX draws the header
// the tool produced and it is compared against the picture the tool produced.
//
// **A round trip through your own encoder and decoder proves nothing.** If both
// sides share a misunderstanding they agree with each other. So the expected
// image comes separately, as "the pixels after conversion", and this side only
// draws.
//
// **Generated by gen_sketch.py. Do not edit by hand.**
// Add a source to sources/ and run regen.py; the next run picks it up.
#include <TinyGFX.h>
#include <TinyGFX/BusCapture.h>
#include <TinyGFX/MemoryTarget.h>
#include <TinyGFX/Image.h>
#include <tgfx_test.h>
'''

BODY = '''
static const int W = %(w)d, H = %(h)d;
static uint16_t gram[W * H];
TinyGFXMemoryTarget panel(gram, W, H);
TinyGFX lcd(panel);

void setup() {
  Serial.begin(115200);
  tgfxTestBegin("image_oracle");
  lcd.begin();
%(cases)s
  tgfxTestDone();
}
void loop() {}
'''

# **An image with transparency is drawn over a colour it does not contain.**
# On black it would pass either way: a decoder that painted the transparent
# pixels black instead of leaving them alone gives the same picture. Magenta
# does not survive that mistake.
BG_OPAQUE = 0x0000
BG_TRANSPARENT = 0xF81F

CASE = '''
  // ---- %(name)s (%(ops)s) ----
  panel.fillBuffer(%(bg)#06x);
  lcd.drawImage(&%(name)sRef, 0, 0);
  tgfxShot("%(name)s", gram, W, H);
'''


def cases():
    """[(name, width, height, ops, background), ...].

    **The converter's own picture decides the background.** Where it wrote a
    fully transparent pixel, the image is drawn over a colour instead of black
    so that leaving a pixel alone and painting it black are different results.
    """
    if not GENERATED.exists():
        return []
    from PIL import Image

    out = []
    for name, ops in REF.findall(GENERATED.read_text()):
        png = EXPECTED / f"{name}.png"
        if not png.exists():
            raise FileNotFoundError(
                f"{name} is in images.h with no expected/{name}.png. "
                "Run regen.py")
        with Image.open(png) as im:
            w, h = im.size
            clear = im.mode == "RGBA" and im.getchannel("A").getextrema()[0] == 0
        out.append((name, w, h, ops,
                    BG_TRANSPARENT if clear else BG_OPAQUE))
    return sorted(out)


def build():
    """Collect the cases and write the sketch. Returns what cases() returned."""
    found = cases()
    if not found:
        # Still has to build with nothing to draw; pytest decides to skip
        (HERE / "image_oracle.ino").write_text(
            HEAD + BODY % {"w": 1, "h": 1, "cases": "  // no images"})
        return []

    # **The canvas is sized to the largest image.** Smaller ones go top left
    w = max(c[1] for c in found)
    h = max(c[2] for c in found)
    body = "".join(CASE % {"name": n, "ops": o, "bg": bg}
                   for n, _, _, o, bg in found)
    (HERE / "image_oracle.ino").write_text(
        HEAD + '#include "images.h"\n'
        + BODY % {"w": w, "h": h, "cases": body})
    return found
