"""Builds the verification sketch from the <name>.h / <name>.ppm pairs in
`pairs/`.

The generator exists so that **adding a pair needs no code**. It runs at pytest
collection time and writes `image_oracle.ino`.
"""

import re
from pathlib import Path

HERE = Path(__file__).parent
PAIRS = HERE / "pairs"

HEAD = '''// **Does a generated image header draw exactly the converter's expected image?**
//
// The oracle specified by GfxImageToolJs spec 15.2. TinyGFX draws the .h the
// tool produced and it is compared against the .ppm the tool produced.
//
// **A round trip through your own encoder and decoder proves nothing.** If both
// sides share a misunderstanding they agree with each other. So the expected
// image comes separately, as "the pixels after conversion", and this side only
// draws.
//
// **Generated by gen_sketch.py. Do not edit by hand.**
// Drop <name>.h and <name>.ppm into pairs/ and the next run picks them up.
#include <TinyGFX.h>
#include <TinyGFX/BusCapture.h>
#include <TinyGFX/MemoryTarget.h>
#include <TinyGFX/Image.h>
#include <tgfx_test.h>
'''

BODY = '''
static const int W = %(w)d, H = %(h)d;
static uint16_t gram[W * H];
TinyGFXMemoryTarget panel(gram, W, H);
TinyGFX lcd(panel);

void setup() {
  Serial.begin(115200);
  tgfxTestBegin("image_oracle");
  lcd.begin();
%(cases)s
  tgfxTestDone();
}
void loop() {}
'''

CASE = '''
  // ---- %(name)s ----
  panel.fillBuffer(0x0000);
  lcd.drawImage(&%(sym)s, 0, 0);
  tgfxShot("%(name)s", gram, W, H);
'''


def ppm_size(path):
    """Read just the width and height of a P6 file."""
    with open(path, "rb") as f:
        magic = f.readline().strip()
        if magic != b"P6":
            raise ValueError(f"{path}: not P6 ({magic!r})")
        line = f.readline()
        while line.startswith(b"#"):
            line = f.readline()
        w, h = (int(v) for v in line.split())
    return w, h


def find_ref_symbol(header):
    """Pick the TinyGFXImageRef symbol name out of a generated header."""
    m = re.search(r"TinyGFXImageRef\s+(\w+)\s*=", Path(header).read_text())
    if not m:
        raise ValueError(f"{header}: no TinyGFXImageRef found")
    return m.group(1)


def build():
    """Collect the pairs and write the sketch. Returns [(name, w, h), ...]."""
    pairs = []
    for h in sorted(PAIRS.glob("*.h")):
        ppm = h.with_suffix(".ppm")
        if not ppm.exists():
            raise FileNotFoundError(f"{h.name} has no matching {ppm.name}")
        w, hh = ppm_size(ppm)
        pairs.append((h.stem, w, hh, find_ref_symbol(h)))

    if not pairs:
        # Still has to build with no pairs at all; pytest decides to skip
        (HERE / "image_oracle.ino").write_text(
            HEAD + BODY % {"w": 1, "h": 1, "cases": "  // no pairs"})
        return []

    # **The canvas is sized to the largest pair.** Smaller ones go top left
    w = max(p[1] for p in pairs)
    h = max(p[2] for p in pairs)
    includes = "".join(f'#include "pairs/{n}.h"\n' for n, _, _, _ in pairs)
    cases = "".join(CASE % {"name": n, "sym": s} for n, _, _, s in pairs)
    (HERE / "image_oracle.ino").write_text(
        HEAD + includes + BODY % {"w": w, "h": h, "cases": cases})
    return [(n, pw, ph) for n, pw, ph, _ in pairs]
