"""Builds the verification sketch from what the converter wrote.

Reads `generated/images.h` - **one bundled header holding every image**, which
is what GfxImageToolJs emits for a folder - and pairs each `TinyGFXImageRef` in
it with the picture of the same name in `expected/`.

The generator exists so that **adding a case needs no code**: drop a `.png` in
`sources/`, name it in `.imagesconfig`, run `regen.py`. It runs at pytest
collection time and writes `image_oracle.ino`.
"""

import re
from pathlib import Path

HERE = Path(__file__).parent
GENERATED = HERE / "generated" / "images.h"
EXPECTED = HERE / "expected"

# `static const TinyGFXImageRef iconRef = {&icon, &tinygfxImageRlepal4Ops};`
REF = re.compile(
    r"static const TinyGFXImageRef\s+(\w+)Ref\s*=\s*"
    r"\{\s*&\w+\s*,\s*&tinygfxImage(\w+)Ops\s*\}")

HEAD = '''// **Does a generated image header draw exactly the converter's expected image?**
//
// The oracle specified by GfxImageToolJs spec 15.2. TinyGFX draws the header
// the tool produced and it is compared against the picture the tool produced.
//
// **A round trip through your own encoder and decoder proves nothing.** If both
// sides share a misunderstanding they agree with each other. So the expected
// image comes separately, as "the pixels after conversion", and this side only
// draws.
//
// **Generated by gen_sketch.py. Do not edit by hand.**
// Add a source to sources/ and run regen.py; the next run picks it up.
#include <TinyGFX.h>
#include <TinyGFX/BusCapture.h>
#include <TinyGFX/MemoryTarget.h>
#include <TinyGFX/Image.h>
#include <tgfx_test.h>
'''

BODY = '''
static const int W = %(w)d, H = %(h)d;
static uint16_t gram[W * H];
TinyGFXMemoryTarget panel(gram, W, H);
TinyGFX lcd(panel);

void setup() {
  Serial.begin(115200);
  tgfxTestBegin("image_oracle");
  lcd.begin();
%(cases)s
  tgfxTestDone();
}
void loop() {}
'''

# The tool's preview flattens transparency onto black, so the canvas starts
# black. **That transparency is honoured at all is not what is measured here** -
# tests/image_fmt/ draws the same image over a background and checks that only
# the transparent pixels let it through.
CASE = '''
  // ---- %(name)s (%(ops)s) ----
  panel.fillBuffer(0x0000);
  lcd.drawImage(&%(name)sRef, 0, 0);
  tgfxShot("%(name)s", gram, W, H);
'''


def cases():
    """[(name, width, height, ops), ...] from the header and the pictures."""
    if not GENERATED.exists():
        return []
    from PIL import Image

    out = []
    for name, ops in REF.findall(GENERATED.read_text()):
        png = EXPECTED / f"{name}.png"
        if not png.exists():
            raise FileNotFoundError(
                f"{name} is in generated/images.h with no expected/{name}.png. "
                "Run regen.py")
        with Image.open(png) as im:
            w, h = im.size
        out.append((name, w, h, ops))
    return sorted(out)


def build():
    """Collect the cases and write the sketch. Returns [(name, w, h, ops), ...]."""
    found = cases()
    if not found:
        # Still has to build with nothing to draw; pytest decides to skip
        (HERE / "image_oracle.ino").write_text(
            HEAD + BODY % {"w": 1, "h": 1, "cases": "  // no images"})
        return []

    # **The canvas is sized to the largest image.** Smaller ones go top left
    w = max(c[1] for c in found)
    h = max(c[2] for c in found)
    body = "".join(CASE % {"name": n, "ops": o} for n, _, _, o in found)
    (HERE / "image_oracle.ino").write_text(
        HEAD + '#include "generated/images.h"\n'
        + BODY % {"w": w, "h": h, "cases": body})
    return found
