// **Does a generated image header draw exactly the converter's expected image?**
//
// The oracle specified by GfxImageToolJs spec 15.2. TinyGFX draws the .h the
// tool produced and it is compared against the .ppm the tool produced.
//
// **A round trip through your own encoder and decoder proves nothing.** If both
// sides share a misunderstanding they agree with each other. So the expected
// image comes separately, as "the pixels after conversion", and this side only
// draws.
//
// **Generated by gen_sketch.py. Do not edit by hand.**
// Drop <name>.h and <name>.ppm into pairs/ and the next run picks them up.
#include <TinyGFX.h>
#include <TinyGFX/BusCapture.h>
#include <TinyGFX/MemoryTarget.h>
#include <TinyGFX/Image.h>
#include <tgfx_test.h>
#include "pairs/tool_alpha.h"
#include "pairs/tool_bitmap_h.h"
#include "pairs/tool_bitmap_v.h"
#include "pairs/tool_icon.h"
#include "pairs/tool_photo.h"

static const int W = 64, H = 32;
static uint16_t gram[W * H];
TinyGFXMemoryTarget panel(gram, W, H);
TinyGFX lcd(panel);

void setup() {
  Serial.begin(115200);
  tgfxTestBegin("image_oracle");
  lcd.begin();

  // ---- tool_alpha ----
  panel.fillBuffer(0x0000);
  lcd.drawImage(&tool_alphaRef, 0, 0);
  tgfxShot("tool_alpha", gram, W, H);

  // ---- tool_bitmap_h ----
  panel.fillBuffer(0x0000);
  lcd.drawImage(&tool_bitmap_hRef, 0, 0);
  tgfxShot("tool_bitmap_h", gram, W, H);

  // ---- tool_bitmap_v ----
  panel.fillBuffer(0x0000);
  lcd.drawImage(&tool_bitmap_vRef, 0, 0);
  tgfxShot("tool_bitmap_v", gram, W, H);

  // ---- tool_icon ----
  panel.fillBuffer(0x0000);
  lcd.drawImage(&tool_iconRef, 0, 0);
  tgfxShot("tool_icon", gram, W, H);

  // ---- tool_photo ----
  panel.fillBuffer(0x0000);
  lcd.drawImage(&tool_photoRef, 0, 0);
  tgfxShot("tool_photo", gram, W, H);

  tgfxTestDone();
}
void loop() {}
