// **Does a generated image header draw exactly the converter's expected image?**
//
// The oracle specified by GfxImageToolJs spec 15.2. TinyGFX draws the header
// the tool produced and it is compared against the picture the tool produced.
//
// **A round trip through your own encoder and decoder proves nothing.** If both
// sides share a misunderstanding they agree with each other. So the expected
// image comes separately, as "the pixels after conversion", and this side only
// draws.
//
// **Generated by gen_sketch.py. Do not edit by hand.**
// Add a source to sources/ and run regen.py; the next run picks it up.
#include <TinyGFX.h>
#include <TinyGFX/BusCapture.h>
#include <TinyGFX/MemoryTarget.h>
#include <TinyGFX/Image.h>
#include <tgfx_test.h>
#include "generated/images.h"

static const int W = 64, H = 64;
static uint16_t gram[W * H];
TinyGFXMemoryTarget panel(gram, W, H);
TinyGFX lcd(panel);

void setup() {
  Serial.begin(115200);
  tgfxTestBegin("image_oracle");
  lcd.begin();

  // ---- alpha (Rlepal4) ----
  panel.fillBuffer(0xf81f);
  lcd.drawImage(&alphaRef, 0, 0);
  tgfxShot("alpha", gram, W, H);

  // ---- bands (Rle565) ----
  panel.fillBuffer(0x0000);
  lcd.drawImage(&bandsRef, 0, 0);
  tgfxShot("bands", gram, W, H);

  // ---- grad (Bitmap1h) ----
  panel.fillBuffer(0xf81f);
  lcd.drawImage(&gradRef, 0, 0);
  tgfxShot("grad", gram, W, H);

  // ---- icon (Rlepal4) ----
  panel.fillBuffer(0x0000);
  lcd.drawImage(&iconRef, 0, 0);
  tgfxShot("icon", gram, W, H);

  // ---- mono_h (Bitmap1h) ----
  panel.fillBuffer(0xf81f);
  lcd.drawImage(&mono_hRef, 0, 0);
  tgfxShot("mono_h", gram, W, H);

  // ---- mono_v (Bitmap1v) ----
  panel.fillBuffer(0xf81f);
  lcd.drawImage(&mono_vRef, 0, 0);
  tgfxShot("mono_v", gram, W, H);

  // ---- odd_h (Bitmap1h) ----
  panel.fillBuffer(0xf81f);
  lcd.drawImage(&odd_hRef, 0, 0);
  tgfxShot("odd_h", gram, W, H);

  // ---- odd_rle (Rle565) ----
  panel.fillBuffer(0x0000);
  lcd.drawImage(&odd_rleRef, 0, 0);
  tgfxShot("odd_rle", gram, W, H);

  // ---- odd_v (Bitmap1v) ----
  panel.fillBuffer(0xf81f);
  lcd.drawImage(&odd_vRef, 0, 0);
  tgfxShot("odd_v", gram, W, H);

  // ---- photo (Raw565) ----
  panel.fillBuffer(0x0000);
  lcd.drawImage(&photoRef, 0, 0);
  tgfxShot("photo", gram, W, H);

  // ---- quant (Rlepal4) ----
  panel.fillBuffer(0x0000);
  lcd.drawImage(&quantRef, 0, 0);
  tgfxShot("quant", gram, W, H);

  tgfxTestDone();
}
void loop() {}
