// **Does a generated image header draw exactly the converter's expected image?**
//
// The oracle specified by GfxImageToolJs spec 15.2. TinyGFX draws the .h the
// tool produced and it is compared against the .ppm the tool produced.
//
// **A round trip through your own encoder and decoder proves nothing.** If both
// sides share a misunderstanding they agree with each other. So the expected
// image comes separately, as "the pixels after conversion", and this side only
// draws.
//
// **Generated by gen_sketch.py. Do not edit by hand.**
// Drop <name>.h and <name>.ppm into pairs/ and the next run picks them up.
#include <TinyGFX.h>
#include <TinyGFX/BusCapture.h>
#include <TinyGFX/MemoryTarget.h>
#include <TinyGFX/Image.h>
#include <tgfx_test.h>
#include "pairs/icon_raw565.h"
#include "pairs/icon_rle565.h"
#include "pairs/icon_rlepal4.h"
#include "pairs/mono_h.h"
#include "pairs/mono_v.h"

static const int W = 32, H = 32;
static uint16_t gram[W * H];
TinyGFXMemoryTarget panel(gram, W, H);
TinyGFX lcd(panel);

void setup() {
  Serial.begin(115200);
  tgfxTestBegin("image_oracle");
  lcd.begin();

  // ---- icon_raw565 ----
  panel.fillBuffer(0x0000);
  lcd.drawImage(&icon_raw565Ref, 0, 0);
  tgfxShot("icon_raw565", gram, W, H);

  // ---- icon_rle565 ----
  panel.fillBuffer(0x0000);
  lcd.drawImage(&icon_rle565Ref, 0, 0);
  tgfxShot("icon_rle565", gram, W, H);

  // ---- icon_rlepal4 ----
  panel.fillBuffer(0x0000);
  lcd.drawImage(&icon_rlepal4Ref, 0, 0);
  tgfxShot("icon_rlepal4", gram, W, H);

  // ---- mono_h ----
  panel.fillBuffer(0x0000);
  lcd.drawImage(&mono_hRef, 0, 0);
  tgfxShot("mono_h", gram, W, H);

  // ---- mono_v ----
  panel.fillBuffer(0x0000);
  lcd.drawImage(&mono_vRef, 0, 0);
  tgfxShot("mono_v", gram, W, H);

  tgfxTestDone();
}
void loop() {}
