// tgfxDigits — embedded bitmap font
// 
// Generated by LGFX Font Tool JS
// https://github.com/tanakamasayuki/LGFXFontToolJs
// 
// Typeface : lgfxJapanGothic_8
// License  : IPA Font License Agreement v1.0
// Obtained : bundled:lgfxJapanGothic_8
// Copyright: Copyright (c) Information-technology Promotion Agency, Japan (IPA), 2003-2019
// 
// This file contains glyphs rasterized from the typeface above and is a
// derived work of it. Keep this notice with the file and with any binary
// built from it.
// 
// Format   : CellFont v1 — fixed/contiguous 4x6
// Line box : 9px (ascent 7, descent 2)
// Glyphs   : 10
// Data     : 58 bytes
// Coverage : U+0030-U+0039
// 
// Rebuild with:
//   npx lgfx-font build --font lgfxJapanGothic_8 --sets digits --format cellfont --name tgfxDigits --out tests/common_libs/tgfx_font/src/tgfx_digits.h

#pragma once
#include <stdint.h>

// Include your renderer's header (the one providing the CellFont / CellGlyph types) before this file.

#if !defined(CELLFONT_SPEC_VERSION)
#error "Include your renderer CellFont header before this font header"
#elif CELLFONT_SPEC_VERSION != 1
#error "This font header requires CellFont spec version 1"
#endif

// Usage:  display.setFont(&tgfxDigits);

#ifndef LGFXFT_PROGMEM
  #if defined(PROGMEM)
    #define LGFXFT_PROGMEM PROGMEM
  #else
    #define LGFXFT_PROGMEM
  #endif
#endif

static const uint8_t tgfxDigitsBitmaps[30] LGFXFT_PROGMEM = {
  0x6a, 0xdd, 0x66, 0x44, 0x44, 0x44, 0x69, 0x24, 0x8f, 0x62, 0x61, 0x96, 0x26, 0x6a, 0xf2, 0x68,
  0x61, 0x96, 0x68, 0xe9, 0x96, 0xf2, 0x22, 0x44, 0x69, 0x69, 0x96, 0x6a, 0x71, 0xa6
};

static const CellFont tgfxDigits LGFXFT_PROGMEM = {
  tgfxDigitsBitmaps,
  NULL,
  NULL,
  NULL,
  0x30, 10,
  4, 6, 4, 9,
  0, -6,
  3, 0,
};

