// tgfxUtf8 — embedded bitmap font
// 
// Generated by LGFX Font Tool JS
// https://github.com/tanakamasayuki/LGFXFontToolJs
// 
// Typeface : lgfxJapanGothic_8
// License  : IPA Font License Agreement v1.0
// Obtained : bundled:lgfxJapanGothic_8
// Copyright: Copyright (c) Information-technology Promotion Agency, Japan (IPA), 2003-2019
// 
// This file contains glyphs rasterized from the typeface above and is a
// derived work of it. Keep this notice with the file and with any binary
// built from it.
// 
// Format   : CellFont v1 — fixed/sparse 4x6 + fixed/sparse 8x7 (chain of 2)
// Line box : 9px (ascent 7, descent 2) — typeface metrics, for line spacing
// Glyphs   : 13
// Data     : 107 bytes
// Coverage : U+0030-U+0039, U+0041, U+00B0, U+2103
// 
// Rebuild with:
//   npx lgfx-font-tool build --font lgfxJapanGothic_8 --chars '0123456789A°℃' --format cellfont --out tgfx_utf8.h --name tgfxUtf8

#pragma once
#include <stdint.h>

// Include your renderer's header (the one providing the CellFont / CellGlyph types) before this file.

#if !defined(CELLFONT_SPEC_VERSION)
#error "Include your renderer CellFont header before this font header"
#elif CELLFONT_SPEC_VERSION != 1
#error "This font header requires CellFont spec version 1"
#endif

// Usage:  display.setFont(&tgfxUtf8);

#ifndef LGFXFT_PROGMEM
  #if defined(PROGMEM)
    #define LGFXFT_PROGMEM PROGMEM
  #else
    #define LGFXFT_PROGMEM
  #endif
#endif

static const uint8_t tgfxUtf8_2Bitmaps[14] LGFXFT_PROGMEM = {
  0x80, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xb8, 0xc4, 0x40, 0x40, 0x44, 0x38
};

static const uint16_t tgfxUtf8_2Codes[1] LGFXFT_PROGMEM = {
  0x2103
};

static const CellFont tgfxUtf8_2 LGFXFT_PROGMEM = {
  tgfxUtf8_2Bitmaps,
  NULL,
  tgfxUtf8_2Codes,
  NULL,
  0xB0, 2,
  8, 7, 8, 9,
  1, -7,
  7, 1,
};

static const uint8_t tgfxUtf8Bitmaps[33] LGFXFT_PROGMEM = {
  0x6a, 0xdd, 0x66, 0x44, 0x44, 0x44, 0x69, 0x24, 0x8f, 0x62, 0x61, 0x96, 0x26, 0x6a, 0xf2, 0x68,
  0x61, 0x96, 0x68, 0xe9, 0x96, 0xf2, 0x22, 0x44, 0x69, 0x69, 0x96, 0x6a, 0x71, 0xa6, 0x66, 0x66,
  0xa9
};

static const uint16_t tgfxUtf8Codes[1] LGFXFT_PROGMEM = {
  0x0041
};

static const CellFont tgfxUtf8 LGFXFT_PROGMEM = {
  tgfxUtf8Bitmaps,
  NULL,
  tgfxUtf8Codes,
  &tgfxUtf8_2,
  0x30, 11,
  4, 6, 4, 9,
  0, -6,
  3, 10,
};

