// tgfxDigitsSparse — embedded bitmap font
// 
// Generated by LGFX Font Tool JS
// https://github.com/tanakamasayuki/LGFXFontToolJs
// 
// Typeface : lgfxJapanGothic_8
// License  : IPA Font License Agreement v1.0
// Obtained : bundled:lgfxJapanGothic_8
// Copyright: Copyright (c) Information-technology Promotion Agency, Japan (IPA), 2003-2019
// 
// This file contains glyphs rasterized from the typeface above and is a
// derived work of it. Keep this notice with the file and with any binary
// built from it.
// 
// Format   : CellFont v1 — variable/sparse ?x6
// Line box : 9px (ascent 7, descent 2) — typeface metrics, for line spacing
// Glyphs   : 11
// Data     : 109 bytes
// Coverage : U+0030-U+0039, U+2103
// 
// Rebuild with (add --out for wherever this file goes):
//   npx -p lgfx-font-tool lgfx-font build --font lgfxJapanGothic_8 --chars '℃' --sets digits --format cellfont --name tgfxDigitsSparse --max-chain 1

#pragma once
#include <stdint.h>

// Include your renderer's header (the one providing the CellFont / CellGlyph types) before this file.

#if !defined(CELLFONT_SPEC_VERSION)
#error "Include your renderer CellFont header before this font header"
#elif CELLFONT_SPEC_VERSION != 1
#error "This font header requires CellFont spec version 1"
#endif

// Usage:  display.setFont(&tgfxDigitsSparse);

#ifndef LGFXFT_PROGMEM
  #if defined(PROGMEM)
    #define LGFXFT_PROGMEM PROGMEM
  #else
    #define LGFXFT_PROGMEM
  #endif
#endif

static const uint8_t tgfxDigitsSparseBitmaps[35] LGFXFT_PROGMEM = {
  0x6a, 0xdd, 0x66, 0x55, 0x50, 0x69, 0x24, 0x8f, 0x62, 0x61, 0x96, 0x26, 0x6a, 0xf2, 0x68, 0x61,
  0x96, 0x68, 0xe9, 0x96, 0xf2, 0x22, 0x44, 0x69, 0x69, 0x96, 0x6a, 0x71, 0xa6, 0x5c, 0xc4, 0x81,
  0x02, 0x23, 0x80
};

static const CellGlyph tgfxDigitsSparseGlyphs[11] LGFXFT_PROGMEM = {
  { 0, 4, 4 },
  { 3, 2, 4 },
  { 5, 4, 4 },
  { 8, 4, 4 },
  { 11, 4, 4 },
  { 14, 4, 4 },
  { 17, 4, 4 },
  { 20, 4, 4 },
  { 23, 4, 4 },
  { 26, 4, 4 },
  { 29, 7, 8 }
};

static const uint16_t tgfxDigitsSparseCodes[1] LGFXFT_PROGMEM = {
  0x2103
};

static const CellFont tgfxDigitsSparse LGFXFT_PROGMEM = {
  tgfxDigitsSparseBitmaps,
  tgfxDigitsSparseGlyphs,
  tgfxDigitsSparseCodes,
  NULL,
  0x30, 11,
  0, 6, 0, 9,
  0, -6,
  0, 10,
};

