// tgfxDigitsChain — embedded bitmap font
// 
// Generated by LGFX Font Tool JS
// https://github.com/tanakamasayuki/LGFXFontToolJs
// 
// Typeface : lgfxJapanGothic_8
// License  : IPA Font License Agreement v1.0
// Obtained : bundled:lgfxJapanGothic_8
// Copyright: Copyright (c) Information-technology Promotion Agency, Japan (IPA), 2003-2019
// 
// This file contains glyphs rasterized from the typeface above and is a
// derived work of it. Keep this notice with the file and with any binary
// built from it.
// 
// Format   : CellFont v1 — fixed/contiguous 4x6 + fixed/contiguous 6x6 (chain of 2)
// Line box : 9px (ascent 7, descent 2) — typeface metrics, for line spacing
// Glyphs   : 11
// Data     : 91 bytes
// Coverage : U+0030-U+0039, U+2103
// 
// Rebuild with (add --out for wherever this file goes):
//   npx -p lgfx-font-tool lgfx-font build --font lgfxJapanGothic_8 --chars '℃' --sets digits --format cellfont --name tgfxDigitsChain

#pragma once
#include <stdint.h>

// Include your renderer's header (the one providing the CellFont / CellGlyph types) before this file.

#if !defined(CELLFONT_SPEC_VERSION)
#error "Include your renderer CellFont header before this font header"
#elif CELLFONT_SPEC_VERSION != 1
#error "This font header requires CellFont spec version 1"
#endif

// Usage:  display.setFont(&tgfxDigitsChain);

#ifndef LGFXFT_PROGMEM
  #if defined(PROGMEM)
    #define LGFXFT_PROGMEM PROGMEM
  #else
    #define LGFXFT_PROGMEM
  #endif
#endif

static const uint8_t tgfxDigitsChain_2Bitmaps[5] LGFXFT_PROGMEM = {
  0xbb, 0x14, 0x10, 0x44, 0xe0
};

static const CellFont tgfxDigitsChain_2 LGFXFT_PROGMEM = {
  tgfxDigitsChain_2Bitmaps,
  NULL,
  NULL,
  NULL,
  0x2103, 1,
  6, 6, 8, 9,
  1, -6,
  5, 0,
};

static const uint8_t tgfxDigitsChainBitmaps[30] LGFXFT_PROGMEM = {
  0x6a, 0xdd, 0x66, 0x44, 0x44, 0x44, 0x69, 0x24, 0x8f, 0x62, 0x61, 0x96, 0x26, 0x6a, 0xf2, 0x68,
  0x61, 0x96, 0x68, 0xe9, 0x96, 0xf2, 0x22, 0x44, 0x69, 0x69, 0x96, 0x6a, 0x71, 0xa6
};

static const CellFont tgfxDigitsChain LGFXFT_PROGMEM = {
  tgfxDigitsChainBitmaps,
  NULL,
  NULL,
  &tgfxDigitsChain_2,
  0x30, 10,
  4, 6, 4, 9,
  0, -6,
  3, 0,
};

