#!/usr/bin/env python3
"""TinyGFX の固定幅フォントヘッダを生成する。

グリフは下の ART に ASCII アートで書く。5x7 を 6x8 のセルに置き、
列優先（1 バイト = 縦 8 画素、bit0 が上）でパックする。

    python3 tools/gen_font.py            # 生成して書き出す
    python3 tools/gen_font.py --check    # 生成せずレンダリングして目視確認

Phase 0 では 0x20-0x3F（記号と数字）だけ収録している。
英字は Phase 3 でここに足す。
"""
import argparse
import pathlib

CELL_W = 6   # 送り幅（グリフ 5 + 空き 1）
GLYPH_W = 5
CELL_H = 8   # ページ 1 枚
GLYPH_H = 7

FIRST = 0x20

ART = r"""
0x20 space
.....
.....
.....
.....
.....
.....
.....
0x21 !
..#..
..#..
..#..
..#..
..#..
.....
..#..
0x22 "
.#.#.
.#.#.
.....
.....
.....
.....
.....
0x23 #
.#.#.
.#.#.
#####
.#.#.
#####
.#.#.
.#.#.
0x24 $
..#..
.####
#.#..
.###.
..#.#
####.
..#..
0x25 %
##..#
##..#
...#.
..#..
.#...
#..##
#..##
0x26 &
.##..
#..#.
#.#..
.#...
#.#.#
#..#.
.##.#
0x27 '
..#..
..#..
.....
.....
.....
.....
.....
0x28 (
...#.
..#..
.#...
.#...
.#...
..#..
...#.
0x29 )
.#...
..#..
...#.
...#.
...#.
..#..
.#...
0x2A *
.....
#.#.#
.###.
#####
.###.
#.#.#
.....
0x2B +
.....
..#..
..#..
#####
..#..
..#..
.....
0x2C ,
.....
.....
.....
.....
.....
..##.
.##..
0x2D -
.....
.....
.....
#####
.....
.....
.....
0x2E .
.....
.....
.....
.....
.....
.##..
.##..
0x2F /
....#
...#.
...#.
..#..
.#...
.#...
#....
0x30 0
.###.
#...#
#..##
#.#.#
##..#
#...#
.###.
0x31 1
..#..
.##..
..#..
..#..
..#..
..#..
.###.
0x32 2
.###.
#...#
....#
...#.
..#..
.#...
#####
0x33 3
#####
...#.
..#..
...#.
....#
#...#
.###.
0x34 4
...#.
..##.
.#.#.
#..#.
#####
...#.
...#.
0x35 5
#####
#....
####.
....#
....#
#...#
.###.
0x36 6
..##.
.#...
#....
####.
#...#
#...#
.###.
0x37 7
#####
....#
...#.
..#..
.#...
.#...
.#...
0x38 8
.###.
#...#
#...#
.###.
#...#
#...#
.###.
0x39 9
.###.
#...#
#...#
.####
....#
...#.
.##..
0x3A :
.....
.##..
.##..
.....
.##..
.##..
.....
0x3B ;
.....
.##..
.##..
.....
.##..
..#..
.#...
0x3C <
...#.
..#..
.#...
#....
.#...
..#..
...#.
0x3D =
.....
.....
#####
.....
#####
.....
.....
0x3E >
.#...
..#..
...#.
....#
...#.
..#..
.#...
0x3F ?
.###.
#...#
....#
...#.
..#..
.....
..#..
"""


def parse():
    glyphs = []
    lines = [ln for ln in ART.splitlines() if ln.strip() != ""]
    i = 0
    while i < len(lines):
        header = lines[i]
        assert header.startswith("0x"), f"header expected: {header!r}"
        code = int(header.split()[0], 16)
        rows = lines[i + 1:i + 1 + GLYPH_H]
        assert len(rows) == GLYPH_H, f"{header}: {len(rows)} rows"
        for r in rows:
            assert len(r) == GLYPH_W, f"{header}: row width {len(r)} != {GLYPH_W} ({r!r})"
        glyphs.append((code, rows))
        i += 1 + GLYPH_H
    for n, (code, _) in enumerate(glyphs):
        assert code == FIRST + n, f"non-contiguous at {code:#04x} (expected {FIRST + n:#04x})"
    return glyphs


def pack_gfx(glyphs):
    """GFXfont 形式にパックする。

    行を連結した MSB first のビット列。グリフ間はバイト境界で揃える。
    （LGFXFontToolJs src/format/gfxfont.js と同じ規約）
    """
    bitmap = []
    table = []
    for code, rows in glyphs:
        offset = len(bitmap)
        buf, nbits = 0, 0
        for r in range(GLYPH_H):
            for c in range(GLYPH_W):
                buf = (buf << 1) | (1 if rows[r][c] == "#" else 0)
                nbits += 1
                if nbits == 8:
                    bitmap.append(buf & 0xFF)
                    buf, nbits = 0, 0
        if nbits:  # グリフ末尾をバイト境界まで詰める
            bitmap.append((buf << (8 - nbits)) & 0xFF)
        table.append((code, offset, GLYPH_W, GLYPH_H, CELL_W, 0, -GLYPH_H))
    return bitmap, table


def render(code, rows):
    print(f"--- {code:#04x} {chr(code)!r}")
    for r in rows:
        print(r.replace(".", " ").replace("#", "#"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="生成せずレンダリングだけする")
    ap.add_argument("--out", default="tests/fonts/tinygfx_font5x7.h")
    args = ap.parse_args()

    glyphs = parse()
    if args.check:
        for code, rows in glyphs:
            render(code, rows)
        return

    bitmap, table = pack_gfx(glyphs)
    last = FIRST + len(glyphs) - 1

    lines = []
    for i in range(0, len(bitmap), 12):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in bitmap[i:i + 12]) + ",")
    tbl = []
    for code, off, w, h, adv, xo, yo in table:
        tbl.append(f"    {{{off}, {w}, {h}, {adv}, {xo}, {yo}}},  // {code:#04x} {chr(code)!r}")

    total = len(bitmap) + len(table) * 7
    root = pathlib.Path(__file__).resolve().parent.parent
    out = root / args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "// TinyGFX 5x7 font (generated by tools/gen_font.py - do not edit)\n"
        "//\n"
        f"// 収録: {FIRST:#04x}..{last:#04x}（{len(glyphs)} 文字）\n"
        f"// データ量: bitmap {len(bitmap)} B + glyph 表 {len(table) * 7} B = {total} B\n"
        "//\n"
        "// これは Phase 0 の測定用に自前生成したつなぎのフォント。\n"
        "// 実運用のフォントは LGFXFontToolJs で作る（docs/DECISIONS.ja.md D17）。\n"
        "// TinyGFX 本体はフォントデータを同梱しない。スケッチ側に置くこと。\n"
        "#pragma once\n"
        "#include <TinyGFX/Font.h>\n"
        "#include <stdint.h>\n"
        "\n"
        f"static const uint8_t tinygfxFont5x7Bitmaps[{len(bitmap)}] TINYGFX_FONT_PROGMEM = {{\n"
        + "\n".join(lines)
        + "\n};\n\n"
        f"static const GFXglyph tinygfxFont5x7Glyphs[{len(table)}] TINYGFX_FONT_PROGMEM = {{\n"
        + "\n".join(tbl)
        + "\n};\n\n"
        "static const GFXfont tinygfxFont5x7 TINYGFX_FONT_PROGMEM = {\n"
        "    (uint8_t*)tinygfxFont5x7Bitmaps,\n"
        "    (GFXglyph*)tinygfxFont5x7Glyphs,\n"
        f"    {FIRST:#04x}, {last:#04x}, {CELL_H},\n"
        "};\n",
        encoding="utf-8",
    )
    print(f"wrote {out} ({len(glyphs)} glyphs, bitmap {len(bitmap)} B, table {len(table) * 7} B)")


if __name__ == "__main__":
    main()
