#!/usr/bin/env python3
"""TinyGFX の固定幅フォントヘッダを生成する。

グリフは下の ART に ASCII アートで書く。5x7 を 6x8 のセルに置き、
列優先（1 バイト = 縦 8 画素、bit0 が上）でパックする。

    python3 tools/gen_font.py            # 生成して書き出す
    python3 tools/gen_font.py --check    # 生成せずレンダリングして目視確認

Phase 0 では 0x20-0x3F（記号と数字）だけ収録している。
英字は Phase 3 でここに足す。
"""
import argparse
import pathlib

CELL_W = 6   # 送り幅（グリフ 5 + 空き 1）
GLYPH_W = 5
CELL_H = 8   # ページ 1 枚
GLYPH_H = 7

FIRST = 0x20

ART = r"""
0x20 space
.....
.....
.....
.....
.....
.....
.....
0x21 !
..#..
..#..
..#..
..#..
..#..
.....
..#..
0x22 "
.#.#.
.#.#.
.....
.....
.....
.....
.....
0x23 #
.#.#.
.#.#.
#####
.#.#.
#####
.#.#.
.#.#.
0x24 $
..#..
.####
#.#..
.###.
..#.#
####.
..#..
0x25 %
##..#
##..#
...#.
..#..
.#...
#..##
#..##
0x26 &
.##..
#..#.
#.#..
.#...
#.#.#
#..#.
.##.#
0x27 '
..#..
..#..
.....
.....
.....
.....
.....
0x28 (
...#.
..#..
.#...
.#...
.#...
..#..
...#.
0x29 )
.#...
..#..
...#.
...#.
...#.
..#..
.#...
0x2A *
.....
#.#.#
.###.
#####
.###.
#.#.#
.....
0x2B +
.....
..#..
..#..
#####
..#..
..#..
.....
0x2C ,
.....
.....
.....
.....
.....
..##.
.##..
0x2D -
.....
.....
.....
#####
.....
.....
.....
0x2E .
.....
.....
.....
.....
.....
.##..
.##..
0x2F /
....#
...#.
...#.
..#..
.#...
.#...
#....
0x30 0
.###.
#...#
#..##
#.#.#
##..#
#...#
.###.
0x31 1
..#..
.##..
..#..
..#..
..#..
..#..
.###.
0x32 2
.###.
#...#
....#
...#.
..#..
.#...
#####
0x33 3
#####
...#.
..#..
...#.
....#
#...#
.###.
0x34 4
...#.
..##.
.#.#.
#..#.
#####
...#.
...#.
0x35 5
#####
#....
####.
....#
....#
#...#
.###.
0x36 6
..##.
.#...
#....
####.
#...#
#...#
.###.
0x37 7
#####
....#
...#.
..#..
.#...
.#...
.#...
0x38 8
.###.
#...#
#...#
.###.
#...#
#...#
.###.
0x39 9
.###.
#...#
#...#
.####
....#
...#.
.##..
0x3A :
.....
.##..
.##..
.....
.##..
.##..
.....
0x3B ;
.....
.##..
.##..
.....
.##..
..#..
.#...
0x3C <
...#.
..#..
.#...
#....
.#...
..#..
...#.
0x3D =
.....
.....
#####
.....
#####
.....
.....
0x3E >
.#...
..#..
...#.
....#
...#.
..#..
.#...
0x3F ?
.###.
#...#
....#
...#.
..#..
.....
..#..
"""


def parse():
    glyphs = []
    lines = [ln for ln in ART.splitlines() if ln.strip() != ""]
    i = 0
    while i < len(lines):
        header = lines[i]
        assert header.startswith("0x"), f"header expected: {header!r}"
        code = int(header.split()[0], 16)
        rows = lines[i + 1:i + 1 + GLYPH_H]
        assert len(rows) == GLYPH_H, f"{header}: {len(rows)} rows"
        for r in rows:
            assert len(r) == GLYPH_W, f"{header}: row width {len(r)} != {GLYPH_W} ({r!r})"
        glyphs.append((code, rows))
        i += 1 + GLYPH_H
    for n, (code, _) in enumerate(glyphs):
        assert code == FIRST + n, f"non-contiguous at {code:#04x} (expected {FIRST + n:#04x})"
    return glyphs


def pack(glyphs):
    """行を連結した MSB first のビット列。グリフ間はバイト境界揃え。

    GFXfont / LGFXFontToolJs (src/format/gfxfont.js) と同じ規約。
    """
    bitmap, offsets = [], []
    for _code, rows in glyphs:
        offsets.append(len(bitmap))
        buf, nbits = 0, 0
        for r in range(GLYPH_H):
            for c in range(GLYPH_W):
                buf = (buf << 1) | (1 if rows[r][c] == "#" else 0)
                nbits += 1
                if nbits == 8:
                    bitmap.append(buf & 0xFF)
                    buf, nbits = 0, 0
        if nbits:  # グリフ末尾をバイト境界まで詰める
            bitmap.append((buf << (8 - nbits)) & 0xFF)
    return bitmap, offsets


def render(code, rows):
    print(f"--- {code:#04x} {chr(code)!r}")
    for r in rows:
        print(r)


def hexrows(values, per_line=12, fmt="0x{:02X}"):
    out = []
    for i in range(0, len(values), per_line):
        out.append("    " + ", ".join(fmt.format(v) for v in values[i:i + per_line]) + ",")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="生成せずレンダリングだけする")
    ap.add_argument("--mode", choices=["fixed", "records"], default="fixed",
                    help="fixed=グリフ表を持たない（固定ピッチ） / records=4 バイト/字のグリフ表")
    ap.add_argument("--sparse", action="store_true", help="連続索引ではなく昇順のコード表を持つ")
    ap.add_argument("--symbol", default="tinygfxFont5x7")
    ap.add_argument("--out", default="tests/common_libs/tgfx_font/src/tinygfx_font5x7.h")
    args = ap.parse_args()

    glyphs = parse()
    if args.check:
        for code, rows in glyphs:
            render(code, rows)
        return

    bitmap, offsets = pack(glyphs)
    bytes_per_glyph = (GLYPH_W * GLYPH_H + 7) // 8
    sym = args.symbol
    last = FIRST + len(glyphs) - 1

    parts = [
        "// TinyGFX TinyFont (generated by tools/gen_font.py - do not edit)",
        "//",
        f"// 収録: {FIRST:#04x}..{last:#04x}（{len(glyphs)} 文字）",
        f"// 索引: {'疎（コード表）' if args.sparse else '連続'} / "
        f"グリフ表: {'あり（4 バイト/字）' if args.mode == 'records' else 'なし（固定ピッチ）'}",
        "//",
        "// Phase 0 の測定用に自前生成したつなぎのフォント。",
        "// 実運用のフォントは LGFXFontToolJs で作る（docs/DECISIONS.ja.md D17）。",
        "// TinyGFX 本体はフォントデータを同梱しない。スケッチ側に置くこと。",
        "#pragma once",
        "#include <TinyGFX/Font.h>",
        "#include <stdint.h>",
        "",
        f"static const uint8_t {sym}Bitmaps[{len(bitmap)}] TINYGFX_FONT_PROGMEM = {{",
        hexrows(bitmap),
        "};",
        "",
    ]

    if args.mode == "records":
        recs = []
        for off in offsets:
            recs.append(f"    {{{off & 0xFF}, {off >> 8}, {GLYPH_W}, {CELL_W}}},")
        parts += [
            f"static const TinyGFXGlyph {sym}Glyphs[{len(offsets)}] TINYGFX_FONT_PROGMEM = {{",
            "\n".join(recs),
            "};",
            "",
        ]

    if args.sparse:
        codes = [code for code, _ in glyphs]
        parts += [
            f"static const uint16_t {sym}Codes[{len(codes)}] TINYGFX_FONT_PROGMEM = {{",
            hexrows(codes, per_line=10, fmt="0x{:04X}"),
            "};",
            "",
        ]

    parts += [
        f"static const TinyGFXFont {sym} TINYGFX_FONT_PROGMEM = {{",
        f"    {sym}Bitmaps,",
        f"    {sym}Glyphs," if args.mode == "records" else "    nullptr,  // 固定ピッチ",
        f"    {sym}Codes," if args.sparse else "    nullptr,  // 連続索引",
        f"    {FIRST:#04x},  // first",
        f"    {len(glyphs)},  // count",
        f"    {GLYPH_W},  // width",
        f"    {GLYPH_H},  // height",
        f"    {CELL_W},  // xAdvance",
        f"    {CELL_H},  // yAdvance",
        "    0,  // xOffset",
        f"    {-GLYPH_H},  // yOffset",
        f"    {bytes_per_glyph},  // bytesPerGlyph",
        "};",
        "",
    ]

    data = len(bitmap)
    if args.mode == "records":
        data += len(offsets) * 4
    if args.sparse:
        data += len(glyphs) * 2

    root = pathlib.Path(__file__).resolve().parent.parent
    out = root / args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {out}")
    print(f"  glyphs={len(glyphs)} bitmap={len(bitmap)}B "
          f"table={len(offsets) * 4 if args.mode == 'records' else 0}B "
          f"codes={len(glyphs) * 2 if args.sparse else 0}B  data={data}B (+ヘッダ約24B)")


if __name__ == "__main__":
    main()
