/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef TINYGFX_VERSION_H
#define TINYGFX_VERSION_H

#define TINYGFX_VERSION_MAJOR 0
#define TINYGFX_VERSION_MINOR 0
#define TINYGFX_VERSION_PATCH 0
#define TINYGFX_VERSION_STR "0.0.0"

#endif // TINYGFX_VERSION_H
