// Straight from the LGFXFontToolJs CLI. Do not hand-edit - the "Rebuild with"
// line below is the tool's own. The symbol name comes from the output file
// name, so keep it font.h.
// font — embedded bitmap font
// 
// Generated by LGFX Font Tool JS
// https://github.com/tanakamasayuki/LGFXFontToolJs
// 
// Typeface : Noto Sans JP
// Author   : Google
// License  : SIL Open Font License 1.1
//            https://openfontlicense.org/
// Obtained : Google Fonts: Noto Sans JP
// Source   : sha256:4593dfcdc70ee68852606c90d75dfc6e022feda12780a55615239c53c54ef086
// 
// This file contains glyphs rasterized from the typeface above and is a
// derived work of it. Keep this notice with the file and with any binary
// built from it.
// 
// Format   : CellFont v1 — variable/sparse ?x11
// Line box : 11px (ascent 10, descent 1) — typeface metrics, for line spacing
// Glyphs   : 12
// Data     : 245 bytes
// Coverage : U+0020, U+002E, U+0032-U+0033, U+0035, U+2103, U+4E86, U+5B8C, U+5B9A, U+5EA6, U+6E29, U+8A2D
// 
// Rebuild with (add --out for wherever this file goes):
//   npx -p lgfx-font-tool lgfx-font build --google 'Noto Sans JP' --em 12 --chars '温度設定完了 23.5℃' --format cellfont --name font

#pragma once
#include <stdint.h>

// Include your renderer's header (the one providing the CellFont / CellGlyph types) before this file.

#if !defined(CELLFONT_SPEC_VERSION)
#error "Include your renderer CellFont header before this font header"
#elif CELLFONT_SPEC_VERSION != 1
#error "This font header requires CellFont spec version 1"
#endif

// Usage:  display.setFont(&font);

#ifndef LGFXFT_PROGMEM
  #if defined(PROGMEM)
    #define LGFXFT_PROGMEM PROGMEM
  #else
    #define LGFXFT_PROGMEM
  #endif
#endif

static const uint8_t fontBitmaps[149] LGFXFT_PROGMEM = {
  0x01, 0xec, 0xc3, 0x0c, 0x21, 0x8c, 0x63, 0xf0, 0x00, 0x01, 0xe4, 0xc3, 0x0c, 0xe0, 0xc1, 0xcd,
  0xe0, 0x00, 0x00, 0x00, 0x00, 0x4c, 0x00, 0x01, 0xf6, 0x10, 0x79, 0x30, 0x43, 0xcd, 0xe0, 0x00,
  0x00, 0x1e, 0x7e, 0x5d, 0xfb, 0x00, 0x40, 0x18, 0x01, 0x00, 0x30, 0x06, 0x20, 0x7c, 0x00, 0x00,
  0x00, 0x0f, 0xfc, 0x03, 0x00, 0xc0, 0x30, 0x0c, 0x01, 0x80, 0x30, 0x06, 0x00, 0xc0, 0x78, 0x00,
  0x06, 0x07, 0xfe, 0x40, 0x25, 0xfe, 0x00, 0x07, 0xfe, 0x7f, 0xe1, 0x90, 0x19, 0x03, 0x13, 0xe1,
  0xe0, 0x06, 0x07, 0xfe, 0x40, 0x25, 0xfe, 0x1f, 0xc1, 0x60, 0x37, 0xc3, 0x60, 0x36, 0x06, 0xe0,
  0xc7, 0xf0, 0x02, 0x07, 0xff, 0x64, 0x87, 0xfe, 0x64, 0x86, 0x78, 0x60, 0x07, 0xfc, 0x44, 0xc4,
  0x78, 0xdf, 0xe0, 0x7f, 0xe1, 0xc6, 0x0f, 0xec, 0xc6, 0x6f, 0xe0, 0x00, 0x1f, 0xe3, 0xaa, 0x2a,
  0xa6, 0xaa, 0x5f, 0xf0, 0x7b, 0xc0, 0x24, 0xfa, 0x57, 0xe7, 0x7c, 0x27, 0xfe, 0x02, 0x67, 0xbc,
  0x49, 0xc7, 0xfe, 0x46, 0x70
};

static const CellGlyph fontGlyphs[12] LGFXFT_PROGMEM = {
  { 0, 6, 7 },
  { 9, 6, 7 },
  { 18, 0, 3 },
  { 18, 3, 3 },
  { 23, 6, 7 },
  { 32, 11, 12 },
  { 48, 11, 12 },
  { 64, 12, 12 },
  { 81, 12, 12 },
  { 98, 12, 12 },
  { 115, 12, 12 },
  { 132, 12, 12 }
};

static const uint16_t fontCodes[10] LGFXFT_PROGMEM = {
  0x0020, 0x002E, 0x0035, 0x2103, 0x4E86, 0x5B8C, 0x5B9A, 0x5EA6,
  0x6E29, 0x8A2D
};

static const CellFont font LGFXFT_PROGMEM = {
  fontBitmaps,
  fontGlyphs,
  fontCodes,
  NULL,
  0x32, 12,
  0, 11, 0, 11,
  0, -10,
  0, 2,
};

